### ISSUE TITLE
Http status code 200(OK) with empty body response

### ISSUE THREAD

**Issue by fabgio** [WeatherXM/docs#41]
Hi am dealing with error situations in developing an API for Weatherxm. I notice that if I submit the REST request:

GET https://api.weatherxm.com/api/v1/cells/871ea0976ffffff/devices

the request is fulfilled  correctly and returns a response with a json  full body; response code  200 OK. 

Afterwards I submit  the same  request this time  passing a different  cell index that generates a  response with an empty body; the response code is 200 OK either.     

This brings a problem in dealing with wrong cell values developing the API  

Would it possible to make Weatherxm station to return status code 204 No Content in case of an empty body respose?

https://en.wikipedia.org/wiki/List_of_HTTP_status_codes
  

Thanks

**Comment by PavlosTze** [comment]
Hello @fabgio , thank you for catching this. We will handle it accordingly and return 204 on empty content. On the next API release the fix will be included.

Please keep in mind that it's better to report such bugs/suggestions to our [issue tracker](https://github.com/WeatherXM/issue-tracker) as this repository is powering the [WeatherXM Documentation site](https://docs.weatherxm.com/) and isn't related to our API.

Thank you,
Pavlos
