### ISSUE TITLE
Glossary of Common Terms' Description of "Relative Humidity" Does Not Fit the Term.

### ISSUE THREAD

**Issue by EmperorDRT1** [WeatherXM/docs#7]
### Issue:
In the Glossary of Common Terms section of the WeatherXM devices page, the description of the Relative Humidity (RH) term refers to an instrument (hygrometer) rather than the description of the term "Relative Humidity (RH)". 

### Solution:
The term should be changed to "hygrometer" or the description should be changed to one describing "Relative Humidity".

**Comment by PavlosTze** [comment]
Thank you @EmperorDRT1 . Fixed. :)
